spring :
  datasource :
    url : jdbc:mysql://47.112.179.125:3306/auth?useUnicode=true&amp;characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username : root
    password : 554535253
    driverClassName : com.mysql.jdbc.Driver
    platform: mysql
    schema: classpath:/schema.sql
    #第一次启动做建表用，之后注释掉
#    initialization-mode: always
mybatis :
  config-location : classpath:/mybatis-config.xml
# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "